config/routes.rb
Rails.application.routes.draw do
  
  get 'test' => 'home#test'
  get 'bondy' => 'home#bondy'
  
  namespace :rapidfire do
  get 'survey_result/makesurvey'
  end

  mount Rapidfire::Engine => "/rapidfire"
  
  
  resources :question_groups do
    get 'results', on: :member
    resources :questions
    resources :answer_groups, only: [:new, :create]
  end
  

  get 'home/about'
  get 'rapidfire/survey_results/makesurvey' => 'rapidfire/survey_results#makesurvey'
  
  devise_scope :user do
    authenticated :user do
      root 'rapidfire/question_groups#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  # devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  
end

app/models/rapidfire/answer.rb
module Rapidfire
  class Answer < ActiveRecord::Base
    belongs_to :question
    belongs_to :answer_group, inverse_of: :answers
    validates :question, :answer_group, presence: true
    validate  :verify_answer_text, :if => "question.present?"
    if Rails::VERSION::MAJOR == 3
      attr_accessible :question_id, :answer_group, :answer_text
    end
    private
    def verify_answer_text
      question.validate_answer(self)
    end
  end
end

app/models/rapidfire/answer_group.rb
module Rapidfire
  class AnswerGroup < ActiveRecord::Base
    belongs_to :question_group
    belongs_to :user, polymorphic: true
    has_many   :answers, inverse_of: :answer_group, autosave: true
    if Rails::VERSION::MAJOR == 3
      attr_accessible :question_group, :user
    end
  end
end

app/models/rapidfire/question.rb
module Rapidfire
  class Question < ActiveRecord::Base
    belongs_to :question_group, :inverse_of => :questions
    has_many   :answers
    default_scope { order(:position) }
    validates :question_group, :question_text, :presence => true
    serialize :validation_rules
    if Rails::VERSION::MAJOR == 3
      attr_accessible :question_group, :question_text, :validation_rules, :answer_options
    end
    def self.inherited(child)
      child.instance_eval do
        def model_name
          Question.model_name
        end
      end
      super
    end
    def rules
      validation_rules || {}
    end
    # answer will delegate its validation to question, and question
    # will inturn add validations on answer on the fly!
    def validate_answer(answer)
      if rules[:presence] == "1"
        answer.validates_presence_of :answer_text
      end
      if rules[:minimum].present? || rules[:maximum].present?
        min_max = { minimum: rules[:minimum].to_i }
        min_max[:maximum] = rules[:maximum].to_i if rules[:maximum].present?
        answer.validates_length_of :answer_text, min_max
      end
    end
  end
end

app/models/rapidfire/question_group.rb
module Rapidfire
  class QuestionGroup < ActiveRecord::Base
      
    belongs_to :user
    has_many   :questions
    
    validates  :user_id, :presence => true
    validates  :name, :presence => true
    validates  :writer, :presence => true
    self.per_page=10
    if Rails::VERSION::MAJOR == 3
      attr_accessible :user_id, :name, :writer
    end
  end
end

app/models/rapidfire/questions/checkbox.rb
module Rapidfire
  module Questions
    class Checkbox < Rapidfire::Question
      validates :answer_options, :presence => true

      def options
        answer_options.split(Rapidfire.answers_delimiter)
      end

      def validate_answer(answer)
        super(answer)

        if rules[:presence] == "1" || answer.answer_text.present?
          answer.answer_text.split(Rapidfire.answers_delimiter).each do |value|
            answer.errors.add(:answer_text, :invalid) unless options.include?(value)
          end
        end
      end
    end
  end
end

app/models/rapidfire/questions/date.rb
module Rapidfire
  module Questions
    class Date < Rapidfire::Question
      def validate_answer(answer)
        super(answer)

        if rules[:presence] == "1" || answer.answer_text.present?
          begin  ::Date.parse(answer.answer_text.to_s)
          rescue ArgumentError => e
            answer.errors.add(:answer_text, :invalid)
          end
        end
      end
    end
  end
end

app/models/rapidfire/questions/long.rb
module Rapidfire
  module Questions
    class Long < Rapidfire::Question
    end
  end
end

app/models/rapidfire/questions/numeric.rb
module Rapidfire
  module Questions
    class Numeric < Rapidfire::Question
      def validate_answer(answer)
        super(answer)

        if rules[:presence] == "1" || answer.answer_text.present?
          gt_or_lt = {}
          if rules[:greater_than_or_equal_to].present?
            gt_or_lt[:greater_than_or_equal_to] = rules[:greater_than_or_equal_to].to_i
          end
          if rules[:less_than_or_equal_to].present?
            gt_or_lt[:less_than_or_equal_to] = rules[:less_than_or_equal_to].to_i
          end

          answer.validates_numericality_of :answer_text, gt_or_lt
        end
      end
    end
  end
end

app/models/rapidfire/questions/radio.rb
module Rapidfire
  module Questions
    class Radio < Select
    end
  end
end

app/models/rapidfire/questions/select.rb
module Rapidfire
  module Questions
    class Select < Rapidfire::Question
      validates :answer_options, :presence => true

      def options
        answer_options.split(Rapidfire.answers_delimiter)
      end

      def validate_answer(answer)
        super(answer)

        if rules[:presence] == "1" || answer.answer_text.present?
          answer.validates_inclusion_of :answer_text, :in => options
        end
      end
    end
  end
end

app/models/rapidfire/questions/short.rb
module Rapidfire
  module Questions
    class Short < Rapidfire::Question
    end
  end
end

app/controllers/rapidfire/answer_groups_controller.rb
module Rapidfire
  class AnswerGroupsController < Rapidfire::ApplicationController
    before_filter :find_question_group!
    def new
      @answer_group_builder = AnswerGroupBuilder.new(answer_group_params)
    end
    def create
      @userinfo = User.find_by_id(current_user.id)
      @userinfo.point += 10
      @userinfo.submitnum += 1
      @userinfo.save
      @answer_group_builder = AnswerGroupBuilder.new(answer_group_params)
      if @answer_group_builder.save
        redirect_to question_groups_path
      else
        render :new
      end
    end
    
    private
    def find_question_group!
      @question_group = QuestionGroup.find(params[:question_group_id])
    end
    def answer_group_params
      answer_params = { params: params[:answer_group] }
      answer_params.merge(user: current_user, question_group: @question_group)
    end
  end
end

app/controllers/rapidfire/question_groups_controller.rb
module Rapidfire
  class QuestionGroupsController < Rapidfire::ApplicationController
    before_filter :authenticate_administrator!, :except => [:index]
    respond_to :html  
    # respond_to :json, only: :results
    include ApplicationHelper
    
    def index
      @posts = QuestionGroup.order('created_at DESC').paginate :page => params[:page]
      @my_question_groups= QuestionGroup.where(:user_id => current_user.id)
      
      @my_answer_groups = AnswerGroup.where(:user_id => current_user.id)
     
      @question_groups = QuestionGroup.all.reverse
      respond_with(@question_groups)
    end

    
    def new
      @question_group = QuestionGroup.new
      respond_with(@question_group)
    end
    
    def create
      @userinfo = User.find_by_id(current_user.id)
      @userinfo.point -= 10
      @userinfo.postnum += 1
      @userinfo.save
  
      @question_group = QuestionGroup.new(question_group_params)
      # @question_group.user_id = current_user.id
      # # @question_group.writer = current_user.username
      # @question_group.save
      # respond_with(@question_group, location: question_group_questions_path(@question_group))
      
      if @question_group.save
        respond_to do |format|
          format.html { redirect_to question_group_questions_path(@question_group) }
          format.js
        end
      else
        respond_to do |format|
          format.html { render :new }
          format.js
        end
      end
      
    end
    
    def show
      redirect_to "/rapidfire"
    # doesn't need to assign the flash notice to the template, that's done automatically
    end
    
    def destroy
      @question_group = QuestionGroup.find(params[:id])
      @question_group.destroy
      
      # respond_with(@question_group)
      
      respond_to do |format|
        format.html { redirect_to question_group_path }
        format.js
      end
    end
    
    def results
      @question_group = QuestionGroup.find(params[:id])
      @question_group_results =
        QuestionGroupResults.new(question_group: @question_group).extract
      # respond_with(@question_group_results, root: false)
      
      respond_to do |format|
        format.json { render json: @question_group_results, root: false }
        format.html
        format.js
      end
    end
    
    
    private
    def question_group_params
      if Rails::VERSION::MAJOR == 4
        params.require(:question_group).permit(:user_id, :name, :writer)
      else
        params[:question_group]
      end
    end
  end
end

app/controllers/rapidfire/questions_controller.rb
module Rapidfire
  class QuestionsController < Rapidfire::ApplicationController
    before_filter :authenticate_administrator!
    respond_to :html, :js
    before_filter :find_question_group!
    before_filter :find_question!, :only => [:edit, :update, :destroy]
    
    def index
      @questions = @question_group.questions
      respond_with(@questions)
    end
    
    def new
      @question = QuestionForm.new(:question_group => @question_group)
      respond_with(@question)
    end
    
    def create
      form_params = params[:question].merge(:question_group => @question_group)
      @question = QuestionForm.new(form_params)
      @question.save
      respond_with(@question, location: index_location)
    end
    
    def edit
      @question = QuestionForm.new(:question => @question)
      @question_group_name = @question_group.name
      respond_with(@question)
    end
    
    def update
      form_params = params[:question].merge(:question => @question)
      @question = QuestionForm.new(form_params)
      @question.save
      respond_with(@question, location: index_location)
    end
    
    def destroy
      @question.destroy
      # respond_with(@question, location: index_location)
      respond_to do |format|
        format.html { redirect_to index_location }
        format.js
      end
    end
    
    private
    
    def save_and_redirect(params, on_error_key)
      @question_form = QuestionForm.new(params)
      @question_form.save

      if @question_form.errors.empty?
        respond_to do |format|
          format.html { redirect_to index_location }
          format.js
        end
      else
        respond_to do |format|
          format.html { render on_error_key.to_sym }
          format.js
        end
      end
    end
    
    def find_question_group!
      @question_group = QuestionGroup.find(params[:question_group_id])
    end
    
    def find_question!
      @question = @question_group.questions.find(params[:id])
    end
    
    def index_location
      rapidfire.question_group_questions_url(@question_group)
    end
  end
end

app/controllers/rapidfire_controller.rb
class RapidfireController < ApplicationController
 
end

app/helpers/rapidfire/application_helper.rb
module Rapidfire
  module ApplicationHelper
    def render_answer_form_helper(answer, form)
      partial = answer.question.type.to_s.split("::").last.downcase
      render partial: "rapidfire/answers/#{partial}", locals: { f: form, answer: answer }
    end
    def checkbox_checked?(answer, option)
      answers_delimiter = Rapidfire.answers_delimiter
      answers = answer.answer_text.to_s.split(answers_delimiter)
      answers.include?(option)
    end
  end
end

app/helpers/rapidfire_helper.rb
module RapidfireHelper
end

app/views/rapidfire/question_groups/_form.html.erb
<h3><%= question_group.new_record? ? "새 설문 등록" : "기존 설문 수정" %></h3>


<%= form_for question_group do |f| %>
  <%- if question_group.errors.any? %>
    <ul>
      <%- question_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  
  <div class="input-field col s6">
    <%= f.text_field :name, :style => "width:250px; margin-bottom:10px;" %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :writer, :value => current_user.username %>
  </div>
 
  
  <%= f.submit '등록하기',:class => "btn btn-primary", :style => "margin-right:5px; width:120px;  height:30px;" %>
  <a href="/" class="btn btn-default" role="button" style="width:120px; height:30px;">뒤로 가기</a>

 
<% end %>

app/views/rapidfire/question_groups/_html_results.html.erb
<% results.each do |result| %>
  <div>
    <h4>
      Question:
      <%= result.question.question_text %>
    </h4>
    <p>
      <% if result.results.is_a?(Array) %>
        <ol>
          <% result.results.each do |answer| %>
            <li>
            <%= answer %>
            </li>
          <% end %>
        </ol>
      <% else if result.results.is_a?(Hash) %>
        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>Option</th>
              <th>Count</th>
            </tr>
          </thead>
          <tbody>
            <% result.results.each do |option, count| %>
              <tr>
                <td>
                  <%= option %>
                </td>
                <td>
                  <%= count %>
                </td>
                
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
      <% end %>
    </p>
    
  </div>
  
  <hr/>
<% end %>

app/views/rapidfire/question_groups/_json_results.html.erb
<div id="js-json-results"></div>
<script>
  var charts = new ResultChart("#{question_group.id}");
  charts.render();        
</script>


<html>
  <% @question_group_results.each do |result| %>
    <% if result.results.is_a?(Array) %>
      <% result.results.each do |answer| %>
       <%= result.question.question_text %>
      <% end %>
    
      <head>
        <%else if result.results.is_a?(Hash) %>
     
        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
        <script type="text/javascript">
         google.charts.load('current', {'packages':['corechart']});
         google.charts.setOnLoadCallback(drawChart);
         
          function drawChart() {
            var data = google.visualization.arrayToDataTable([
               ['option', 'count'],
               <%- result.results.each do |option, count| %>
                            ["<%=option%>",<%=count%>],
              <% end %>
            ]);
            var options = {
              title: '<%= result.question.question_text %>'
            };
            var chart = new google.visualization.PieChart(document.getElementById('piechart'));
            chart.draw(data, options);
            
          }
           
        </script>
         
          
        <div id="piechart" style="width:800px; height: 500px;"></div>
        <% end %>
       
      </head>
       <% end %> 
<% end %>
</html>

app/views/rapidfire/question_groups/_question_group.html.erb
  <% if can_administer? %>
      <th><%= question_group.id%></th>
      <% if current_user.id == question_group.user_id %>
        <th><%= link_to question_group.name, question_group_questions_path(question_group)   %></th>
      
      <% end %>
      <th><%= question_group.writer %></th>
      <th><%= question_group.created_at.in_time_zone("Asia/Seoul").strftime("%Y-%m-%d %H:%M") %></th>
      <th>
        <ul class="horizontal-list">
           <% if current_user.id == question_group.user_id %>
            <% if can_administer? %>
            <li><%= link_to "Results", [:results, question_group] %></li>
            <li><%= link_to "Delete", [question_group], method: :delete %></li>
          <% end %>
          <% else %>
          <li><%= link_to "Answer Questions", new_question_group_answer_group_path(question_group) %></li>
          </ul>
          <% end %>
    </th>
      
    <% else %>
      <%= question_group.name %>
      
    <% end %>

app/views/rapidfire/question_groups/index.html.erb
<div class="col-sm-4 col-md-2 user_box">
      <% if user_signed_in? %>
      <div class="user_box_top">
        <span class="user_name"><%= current_user.username %></span><br>
        <span class="user_email"><%= current_user.point %> 포인트</span><br>
        
        
        <!--<a href="/users/edit"><span class="user_edit">edit</i></a>-->
      </div>
      
      <!--<div class="user_box_bottom">-->
        
      <!--  <div class="user_point"><= current_user.point %><br><span class="point">p</span></div>-->
      <!--  <div class="user_point"><= current_user.postnum %><br><i class="fa fa-pencil-square" aria-hidden="true"></i></div>-->
      <!--  <div class="user_point"><= current_user.submitnum %><br><i class="fa fa-bookmark" aria-hidden="true"></i></div>-->
      <!--</div>-->
      
      <!--<div class="user_box_bottom">-->
        <!--<span class="user_point">포인트 : <= current_user.point %></span><br>-->
      <!--  <span class="user_write">-->
      <!--      <i class="fa fa-pencil-square" aria-hidden="true"></i>작성한설문-->
      <!--      <span style="text-align:right"><= current_user.postnum %></span>-->
      <!--  </span>-->
      <!--</div>-->
      
      <!--<div class="user_box_bottom">-->
        <!--<span class="user_point">포인트 : <= current_user.point %></span><br>-->  
      <!--  <span class="user_do">-->
      <!--      <i class="fa fa-bookmark" aria-hidden="true"></i>참여한 설문-->
      <!--      <= current_user.submitnum %></span>-->
      <!--</div>-->
        

      
        <div class="input-group-btn" style="border-bottom: 1px solid #00b7b6;">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
             <i class="fa fa-pencil-square user-icon" aria-hidden="true"></i>등록한 설문 <%= current_user.postnum %> <span class="caret"></span>
          </button>
         <ul class="dropdown-menu dropdown-menu-right" role="menu">
            <% @my_question_groups.each do |p| %>
              <li><a href="/rapidfire/question_groups/<%= p.id %>/results"><%= p.name %></a> </li>
     	    <% end %>
     		 </ul> 
    </div>
    <br>
    
      <div class="input-group-btn">
     		<button type="button" class="btn btn-default dropdown-toggle aaa" data-toggle="dropdown" aria-expanded="false">
             <i class="fa fa-bookmark user-icon" aria-hidden="true"></i>참여한 설문 <%= current_user.submitnum %> <span class="caret"></span>
        </button>
        <ul class="dropdown-menu dropdown-menu-right" role="menu">
          <% @my_answer_groups.each do |p| %>
         	  <% @question_groups.each do |l| %>
         	    <% if l.id == p.question_group_id %>
         	      <li><a href="/rapidfire/question_groups/<%= l.id %>/results"><%= l.name %></a></li>
         	    <% end %>
         	  <% end %>
           <% end %>
     		</ul> 
     	</div>
     		 
  <% end %>
  
</div>
</div>

<div class="col-xs-12 col-md-10">
    <table class="survey_list">
     
    <colgroup>
    <col width="15%">
    <col width="55%">
    <col width="30%">
    </colgroup> 
   
    <tbody>
      <% @posts.each do |question_group| %>
        <% if can_administer? %>
        <tr>
          <td style="text-align:center"><%= question_group.id%></td>
        
          <td>
          <span class="survey_name"><%= question_group.name%>
            <% if current_user.id == question_group.user_id %>
              <% if can_administer? %>
                <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, question_group_questions_path(question_group), :class => 'survey-icon' %>
                
                <%= link_to '<i class="fa fa-trash"></i>'.html_safe, [question_group], method: :delete, :class => 'survey-icon' %>
              <% end %>
            <% end %>  
          </span><br>
          <p class="survey_info">
            <span><%= question_group.writer %></span>
            <span><i class="fa fa-calendar" aria-hidden="true"></i><%= question_group.created_at.in_time_zone("Asia/Seoul").strftime("%Y-%m-%d %H:%M") %></span>
          </p>
          </td>
          
          <td>
            <ul class="horizontal-list">
              <% if current_user.id == question_group.user_id %>
                <% if can_administer? %>
                  <%= link_to "결과 확인", [:results, question_group], :class => 'survey_btn' %>
                <% end %>
              <% else %>
                <%= link_to "설문 참여", new_question_group_answer_group_path(question_group), :class => 'survey_btn' %>
              <% end %>  
            </ul>
          </td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
    </table>
</div>



  

<div class="container">

  <% if user_signed_in? %>
    <div align="right">
      <table>
        <tr> <td>이름 : <%= current_user.username %> </td></tr>
        <tr> <td> 이메일 :  <%= current_user.email %> </td></tr>
        <tr> <td> 포인트 : <%= current_user.point %> </td></tr>
        <tr> <td> 설문 : <%= current_user.postnum %>회 등록  |   
       <%= current_user.submitnum %>회 참여 </td></tr>
      </table>

      <br>
        <div class="input-group-btn">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
             내가 등록한 설문 <span class="caret"></span>
          </button>
         <ul class="dropdown-menu dropdown-menu-right" role="menu">
          <% if @my_question_groups.empty? %> 
            <li>설문이 없습니다!</li>
          <% else %>
            <% @my_question_groups.each do |p| %>
              <li><a href="/rapidfire/question_groups/<%= p.id %>/results"><%= p.name %></a> </li>
     	      <% end %>
     	    <% end %>
     		 </ul> 
    </div>
    
    <br>
      <div class="input-group-btn">
     		<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
             내가 참여한 설문 <span class="caret"></span>
        </button>
        <ul class="dropdown-menu dropdown-menu-right" role="menu">
          <% @my_answer_groups.each do |p| %>
         	  <% @question_groups.each do |l| %>
         	    <% if l.id == p.question_group_id %>
         	      <li><a href="/rapidfire/question_groups/<%= l.id %>/results"><%= l.name %></a></li>
         	    <% end %>
         	  <% end %>
           <% end %>
     		</ul> 
     	</div>
     		 
  <% end %>
  <hr/>
  

  <table class="table table-condensed table-hover result_table">
   <colgroup>
    <col width="70">
    <col width="200">
    <col width="80">
    <col width="80">
    <col width="80">
   </colgroup>
    <thead>
      <tr class="info">
        <th>글번호</th>
        <th>글제목</th>
        <th>작성자</th>
        <th>작성시간</th>
        <th>응답 및 질문 추가</th>
      </tr>
    </thead>
  <tbody>
      
    <colgroup>
    <col width="70">
    <col width="200">
    <col width="80">
    <col width="80">
    <col width="80">
    </colgroup>

    <% @posts.each do |question_group| %>

    <% if can_administer? %>
      <td><%= question_group.id%></td>
      <td><%= question_group.name%></td>
      <td><%= question_group.writer %></td>
      <td><%= question_group.created_at.in_time_zone("Asia/Seoul").strftime("%Y-%m-%d %H:%M") %></td>
      <td>
        <ul class="horizontal-list">
          <% if current_user.id == question_group.user_id %>
            <% if can_administer? %>
            <li><%= link_to "질문 추가", question_group_questions_path(question_group) %></li>
            <li><%= link_to "결과 확인", [:results, question_group] %></li>
            <li><%= link_to "설문 삭제", [question_group], method: :delete %></li>
            <% end %>
          <% else %>
            <%= link_to "설문 응답 하기", new_question_group_answer_group_path(question_group) %>
          </ul>
          <% end %>
      </td>
      
    <% else %>
      <%= question_group.name %>
      
    <% end %>
    
   

    </tbody>
     <% end %>
  </table>
  
  <a href="/rapidfire/question_groups/new" class="btn btn-primary" role="button" style="float: right;">글쓰기</a>
<br><br><br>

<div>
 <nav aria-label="..." class="flickr_pagination">
   <%= will_paginate @posts %>
 </nav>
</div>


<footer class="page-footer" style="opacity: 0.5; margin-top:15px;">
  <div class="container">
    <h6 class="black-text" style="padding-bottom: 20px; font-size:13px; line-height: 1.5em;">
               품앗이    |    멋쟁이 사자처럼 2016 4th Hackathon
        <br>멋쟁이 사자처럼 4기 박정은 소현욱 정여진 정유진<br>
        <br>메일 : <a href="mailto:mail">email</a>

  </div>
    <div class="footer-copyright">
      <div class="container">
        <h6 class="grey-text text-base" style="margin-bottom: 10px; font-size:12px;">
        © 2016 Copyright 품앗이, All rights reserved.</h6>
      </div>
    </div>
  

  <!--자바스크립트-->
  <script>
    $( document ).ready(function(){
       $(".button-collapse").sideNav();
    });

  </script>
</footer>


</div>
</div>

app/views/rapidfire/question_groups/new.html.erb
<%= render partial: 'form', locals: {question_group: @question_group} %>
<hr>

>>>>> 설문 등록 시 10point가 차감됩니다.

app/views/rapidfire/question_groups/results.html.erb
<div class="container">
  <h1><%= @question_group.name %></h1>
  
  <html>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
    </script>
  </html>
    
  <ul class="nav nav-tabs">
    <li class="active">
      <%= link_to "JSON Results", "#json-results", "data-toggle" => "tab" %>
    </li>
    <li>
      <%= link_to "HTML Results", "#html-results", "data-toggle" => "tab" %>
    </li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="json-results">
      <%= render partial: "json_results", locals: { question_group: @question_group } %>
    </div>
    <div class="tab-pane" id="html-results">
     <%= render partial: "html_results", locals: { results: @question_group_results } %>
      
    </div>
  </div>
  
  <a href="/" class="btn btn-primary" role="button" style="float: right;">뒤로 가기</a>
</div>